image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -Duser.language=en -Duser.country=US -jar ./artifacts/app-callback.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test -DchromeHeadless=true