image: Ubuntu

stack: jdk 11



branches:
  only:
    - master

build: off

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-callback.jar -P:profile=test &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info "-DchromeHeadless=true"